### ISSUE TITLE
Create class to act as interface with applications

### ISSUE THREAD

**Issue by vaughantnrc** [PerkLab/MCSTrack#35]
We will call it MCast (for now), but this will change once we settle on a more permanent name for the project.

(Keiran feel free to upload any photos of the whiteboard if it helps to keep things organized and in one place)

**Comment by lassoan** [comment]
> We will call it MCast (for now)

Changing names will be just harder as more code is added. Could we settle on a name now?

I agree that MCSTrack is a bit cumbersome, so let's choose something easier.

For example, what do you think about `MultiCamTracker`, and in code we could use the `Mct` prefix (instead of `MCast`)?

**Comment by vaughantnrc** [comment]
> For example, what do you think about MultiCamTracker, and in code we could use the Mct prefix (instead of MCast)?

Personally, I like it.

**Comment by vaughantnrc** [comment]
As discussed, this now exists, as shown by example in #91.
