### ISSUE TITLE
Add Board-related logic to Pose Solver

### ISSUE THREAD

**Issue by vaughantnrc** [PerkLab/MCSTrack#8]
Related to #6

**Comment by tavaughan** [comment]
@Rampex1 This issue refers to code that is still on NRC's gitlabc. Right now the Pose Solver only tracks single markers. If I remember correctly, the strategy for tracking a board would look something like this:

1. If multiple detectors see the target, build a geometry based on point visibility.
  - If multiple detectors see the same points (markers) and the reference, use intersection of rays as points
  - If only one detector sees points (markers) and the reference, represent the rays as lines
  - Then use an iterative closest point algorithm (combination of point-to-point and point-to-line) to determine the transform from the target to the reference
2. If only one detector sees the target, use `solvePnP` to determine transform from target to detector

The logic exists in code on gitlabc. I can migrate it later. I think it makes sense to unassign yourself from this issue.

**Comment by vaughantnrc** [comment]
#80 shall theoretically address the missing logic in pose solver, though we still lack means of _sending_ the target board to the pose solver.

**Comment by vaughantnrc** [comment]
Issue for _sending_ the target board to the pose solver: https://github.com/PerkLab/MCSTrack/issues/84
